import { PrismaClient } from "@prisma/client";
const prisma = new PrismaClient();

const colleges = [
  { name:"IIT Bombay", location:"Mumbai, Maharashtra", city:"Mumbai", state:"Maharashtra", fees:250000, rating:4.9, courses:JSON.stringify(["B.Tech","M.Tech","MBA","PhD"]), placement:98.5, avgPackage:2800000, topCompanies:JSON.stringify(["Google","Microsoft","Goldman Sachs","McKinsey"]), image:null, tier:"A+", examAccepted:JSON.stringify(["JEE Advanced"]), established:1958, totalSeats:1200 },
  { name:"IIT Delhi", location:"New Delhi, Delhi", city:"New Delhi", state:"Delhi", fees:250000, rating:4.9, courses:JSON.stringify(["B.Tech","M.Tech","MBA","PhD"]), placement:97.8, avgPackage:2600000, topCompanies:JSON.stringify(["Amazon","Apple","BCG","Flipkart"]), image:null, tier:"A+", examAccepted:JSON.stringify(["JEE Advanced"]), established:1961, totalSeats:1100 },
  { name:"IIT Madras", location:"Chennai, Tamil Nadu", city:"Chennai", state:"Tamil Nadu", fees:245000, rating:4.8, courses:JSON.stringify(["B.Tech","M.Tech","PhD","MBA"]), placement:97.2, avgPackage:2500000, topCompanies:JSON.stringify(["Qualcomm","Samsung","Deloitte","Infosys"]), image:null, tier:"A+", examAccepted:JSON.stringify(["JEE Advanced"]), established:1959, totalSeats:1050 },
  { name:"IIT Kanpur", location:"Kanpur, Uttar Pradesh", city:"Kanpur", state:"Uttar Pradesh", fees:240000, rating:4.8, courses:JSON.stringify(["B.Tech","M.Tech","PhD"]), placement:96.5, avgPackage:2400000, topCompanies:JSON.stringify(["Intel","Cisco","Microsoft","Oracle"]), image:null, tier:"A+", examAccepted:JSON.stringify(["JEE Advanced"]), established:1959, totalSeats:960 },
  { name:"IIT Kharagpur", location:"Kharagpur, West Bengal", city:"Kharagpur", state:"West Bengal", fees:235000, rating:4.7, courses:JSON.stringify(["B.Tech","M.Tech","MBA","Law","PhD"]), placement:95.8, avgPackage:2200000, topCompanies:JSON.stringify(["TCS","Wipro","HCL","Accenture"]), image:null, tier:"A+", examAccepted:JSON.stringify(["JEE Advanced"]), established:1951, totalSeats:2000 },
  { name:"IIT Roorkee", location:"Roorkee, Uttarakhand", city:"Roorkee", state:"Uttarakhand", fees:235000, rating:4.7, courses:JSON.stringify(["B.Tech","M.Tech","MBA","PhD"]), placement:94.5, avgPackage:2100000, topCompanies:JSON.stringify(["BPCL","L&T","NTPC","Google"]), image:null, tier:"A+", examAccepted:JSON.stringify(["JEE Advanced"]), established:1847, totalSeats:1700 },
  { name:"IIT Hyderabad", location:"Hyderabad, Telangana", city:"Hyderabad", state:"Telangana", fees:240000, rating:4.6, courses:JSON.stringify(["B.Tech","M.Tech","PhD"]), placement:94.0, avgPackage:2000000, topCompanies:JSON.stringify(["Microsoft","Google","Qualcomm","Samsung"]), image:null, tier:"A+", examAccepted:JSON.stringify(["JEE Advanced"]), established:2008, totalSeats:600 },
  { name:"IIT BHU Varanasi", location:"Varanasi, Uttar Pradesh", city:"Varanasi", state:"Uttar Pradesh", fees:235000, rating:4.6, courses:JSON.stringify(["B.Tech","M.Tech","MBA","PhD"]), placement:93.5, avgPackage:1800000, topCompanies:JSON.stringify(["Goldman Sachs","Microsoft","Amazon","Infosys"]), image:null, tier:"A+", examAccepted:JSON.stringify(["JEE Advanced"]), established:1919, totalSeats:1300 },
  { name:"IIT Gandhinagar", location:"Gandhinagar, Gujarat", city:"Gandhinagar", state:"Gujarat", fees:245000, rating:4.5, courses:JSON.stringify(["B.Tech","M.Tech","PhD"]), placement:92.8, avgPackage:1900000, topCompanies:JSON.stringify(["Microsoft","Amazon","Flipkart","Paytm"]), image:null, tier:"A+", examAccepted:JSON.stringify(["JEE Advanced"]), established:2008, totalSeats:550 },
  { name:"IIT Indore", location:"Indore, Madhya Pradesh", city:"Indore", state:"Madhya Pradesh", fees:238000, rating:4.5, courses:JSON.stringify(["B.Tech","M.Tech","PhD"]), placement:91.5, avgPackage:1800000, topCompanies:JSON.stringify(["Microsoft","Amazon","Samsung","Goldman Sachs"]), image:null, tier:"A+", examAccepted:JSON.stringify(["JEE Advanced"]), established:2009, totalSeats:520 },
  { name:"IIT Patna", location:"Patna, Bihar", city:"Patna", state:"Bihar", fees:235000, rating:4.4, courses:JSON.stringify(["B.Tech","M.Tech","PhD"]), placement:90.0, avgPackage:1700000, topCompanies:JSON.stringify(["Amazon","Flipkart","Infosys","Deloitte"]), image:null, tier:"A+", examAccepted:JSON.stringify(["JEE Advanced"]), established:2008, totalSeats:500 },
  { name:"IIT Mandi", location:"Mandi, Himachal Pradesh", city:"Mandi", state:"Himachal Pradesh", fees:237000, rating:4.3, courses:JSON.stringify(["B.Tech","M.Tech","PhD"]), placement:88.5, avgPackage:1600000, topCompanies:JSON.stringify(["Amazon","Flipkart","Wipro","Samsung"]), image:null, tier:"A+", examAccepted:JSON.stringify(["JEE Advanced"]), established:2009, totalSeats:450 },
  { name:"BITS Pilani", location:"Pilani, Rajasthan", city:"Pilani", state:"Rajasthan", fees:480000, rating:4.6, courses:JSON.stringify(["B.Tech","M.Tech","MBA","MSc","PhD"]), placement:93.1, avgPackage:1900000, topCompanies:JSON.stringify(["Samsung","Texas Instruments","Adobe","Flipkart"]), image:null, tier:"A", examAccepted:JSON.stringify(["BITSAT"]), established:1964, totalSeats:2000 },
  { name:"BITS Pilani Goa Campus", location:"Goa, Goa", city:"Goa", state:"Goa", fees:475000, rating:4.5, courses:JSON.stringify(["B.Tech","M.Sc","MSc-Tech"]), placement:91.7, avgPackage:1800000, topCompanies:JSON.stringify(["Samsung","Texas Instruments","Microsoft","Cisco"]), image:null, tier:"A", examAccepted:JSON.stringify(["BITSAT"]), established:2004, totalSeats:1000 },
  { name:"NIT Trichy", location:"Tiruchirappalli, Tamil Nadu", city:"Tiruchirappalli", state:"Tamil Nadu", fees:140000, rating:4.5, courses:JSON.stringify(["B.Tech","M.Tech","MBA","PhD"]), placement:92.3, avgPackage:1600000, topCompanies:JSON.stringify(["Zoho","Infosys","TCS","Cognizant"]), image:null, tier:"A", examAccepted:JSON.stringify(["JEE Main"]), established:1964, totalSeats:1800 },
  { name:"NIT Warangal", location:"Warangal, Telangana", city:"Warangal", state:"Telangana", fees:132000, rating:4.4, courses:JSON.stringify(["B.Tech","M.Tech","MBA","PhD"]), placement:90.6, avgPackage:1350000, topCompanies:JSON.stringify(["Amazon","Deloitte","Infosys","KPMG"]), image:null, tier:"A", examAccepted:JSON.stringify(["JEE Main"]), established:1959, totalSeats:1700 },
  { name:"NIT Surathkal", location:"Mangalore, Karnataka", city:"Mangalore", state:"Karnataka", fees:135000, rating:4.4, courses:JSON.stringify(["B.Tech","M.Tech","PhD"]), placement:91.2, avgPackage:1400000, topCompanies:JSON.stringify(["Amazon","Infosys","Deloitte","KPMG"]), image:null, tier:"A", examAccepted:JSON.stringify(["JEE Main"]), established:1960, totalSeats:1400 },
  { name:"NIT Rourkela", location:"Rourkela, Odisha", city:"Rourkela", state:"Odisha", fees:131000, rating:4.3, courses:JSON.stringify(["B.Tech","M.Tech","MBA","PhD"]), placement:89.4, avgPackage:1200000, topCompanies:JSON.stringify(["Tata Steel","Infosys","Wipro","Cognizant"]), image:null, tier:"A", examAccepted:JSON.stringify(["JEE Main"]), established:1961, totalSeats:1600 },
  { name:"IIIT Hyderabad", location:"Hyderabad, Telangana", city:"Hyderabad", state:"Telangana", fees:400000, rating:4.5, courses:JSON.stringify(["B.Tech","M.Tech","PhD"]), placement:95.2, avgPackage:2200000, topCompanies:JSON.stringify(["Google","Microsoft","Amazon","Flipkart"]), image:null, tier:"A", examAccepted:JSON.stringify(["UGEE","JEE Main"]), established:1998, totalSeats:700 },
  { name:"Delhi Technological University", location:"New Delhi, Delhi", city:"New Delhi", state:"Delhi", fees:160000, rating:4.4, courses:JSON.stringify(["B.Tech","M.Tech","MBA","PhD"]), placement:89.7, avgPackage:1400000, topCompanies:JSON.stringify(["Samsung","Deloitte","Ernst & Young","Capgemini"]), image:null, tier:"A", examAccepted:JSON.stringify(["JEE Main"]), established:1941, totalSeats:2300 },
  { name:"Jadavpur University", location:"Kolkata, West Bengal", city:"Kolkata", state:"West Bengal", fees:20000, rating:4.5, courses:JSON.stringify(["B.Tech","M.Tech","B.Sc","M.Sc","PhD"]), placement:88.9, avgPackage:1200000, topCompanies:JSON.stringify(["TCS","Infosys","Cognizant","Wipro"]), image:null, tier:"A", examAccepted:JSON.stringify(["WBJEE","JEE Main"]), established:1955, totalSeats:1500 },
  { name:"Anna University", location:"Chennai, Tamil Nadu", city:"Chennai", state:"Tamil Nadu", fees:70000, rating:4.2, courses:JSON.stringify(["B.Tech","M.Tech","MBA","MCA","PhD"]), placement:84.3, avgPackage:800000, topCompanies:JSON.stringify(["Zoho","Infosys","TCS","Cognizant"]), image:null, tier:"A", examAccepted:JSON.stringify(["TNEA"]), established:1978, totalSeats:3000 },
  { name:"Thapar Institute of Engineering", location:"Patiala, Punjab", city:"Patiala", state:"Punjab", fees:340000, rating:4.3, courses:JSON.stringify(["B.Tech","M.Tech","MBA","PhD"]), placement:88.4, avgPackage:1100000, topCompanies:JSON.stringify(["Google","Amazon","Microsoft","Cisco"]), image:null, tier:"A", examAccepted:JSON.stringify(["JEE Main"]), established:1956, totalSeats:3000 },
  { name:"Shiv Nadar University", location:"Greater Noida, Uttar Pradesh", city:"Greater Noida", state:"Uttar Pradesh", fees:600000, rating:4.3, courses:JSON.stringify(["B.Tech","M.Tech","MBA","B.Sc","PhD"]), placement:86.5, avgPackage:1300000, topCompanies:JSON.stringify(["HCL","Amazon","Deloitte","EY"]), image:null, tier:"A", examAccepted:JSON.stringify(["JEE Main","SAT"]), established:2011, totalSeats:2500 },
  { name:"Motilal Nehru NIT Prayagraj", location:"Prayagraj, Uttar Pradesh", city:"Prayagraj", state:"Uttar Pradesh", fees:130000, rating:4.3, courses:JSON.stringify(["B.Tech","M.Tech","MBA","PhD"]), placement:89.0, avgPackage:1250000, topCompanies:JSON.stringify(["Google","Amazon","Microsoft","Flipkart"]), image:null, tier:"A", examAccepted:JSON.stringify(["JEE Main"]), established:1961, totalSeats:1500 },
  { name:"NSUT Delhi", location:"New Delhi, Delhi", city:"New Delhi", state:"Delhi", fees:100000, rating:4.2, courses:JSON.stringify(["B.Tech","M.Tech","PhD"]), placement:87.3, avgPackage:1100000, topCompanies:JSON.stringify(["Samsung","Flipkart","Snapdeal","Deloitte"]), image:null, tier:"A", examAccepted:JSON.stringify(["JEE Main"]), established:1983, totalSeats:1400 },
  { name:"College of Engineering Pune", location:"Pune, Maharashtra", city:"Pune", state:"Maharashtra", fees:85000, rating:4.3, courses:JSON.stringify(["B.Tech","M.Tech"]), placement:87.5, avgPackage:1050000, topCompanies:JSON.stringify(["TATA Motors","L&T","Infosys","Cognizant"]), image:null, tier:"A", examAccepted:JSON.stringify(["MHT CET"]), established:1854, totalSeats:1600 },
  { name:"VIT University Vellore", location:"Vellore, Tamil Nadu", city:"Vellore", state:"Tamil Nadu", fees:195000, rating:4.3, courses:JSON.stringify(["B.Tech","M.Tech","MBA","MCA"]), placement:85.4, avgPackage:900000, topCompanies:JSON.stringify(["Infosys","Wipro","TCS","HCL"]), image:null, tier:"B+", examAccepted:JSON.stringify(["VITEEE"]), established:1984, totalSeats:8000 },
  { name:"Manipal Institute of Technology", location:"Manipal, Karnataka", city:"Manipal", state:"Karnataka", fees:270000, rating:4.2, courses:JSON.stringify(["B.Tech","M.Tech","MBA","BCA"]), placement:83.2, avgPackage:850000, topCompanies:JSON.stringify(["Wipro","Infosys","Accenture","IBM"]), image:null, tier:"B+", examAccepted:JSON.stringify(["MET","JEE Main"]), established:1957, totalSeats:6000 },
  { name:"SRM Institute of Science and Technology", location:"Chennai, Tamil Nadu", city:"Chennai", state:"Tamil Nadu", fees:215000, rating:4.1, courses:JSON.stringify(["B.Tech","M.Tech","MBA","BCA","MCA"]), placement:81.5, avgPackage:750000, topCompanies:JSON.stringify(["Infosys","TCS","Wipro","Cognizant"]), image:null, tier:"B+", examAccepted:JSON.stringify(["SRMJEEE","JEE Main"]), established:1985, totalSeats:10000 },
  { name:"PSG College of Technology", location:"Coimbatore, Tamil Nadu", city:"Coimbatore", state:"Tamil Nadu", fees:80000, rating:4.3, courses:JSON.stringify(["B.Tech","M.Tech","MBA","MCA"]), placement:87.6, avgPackage:900000, topCompanies:JSON.stringify(["Zoho","KONE","Bosch","ABB"]), image:null, tier:"B+", examAccepted:JSON.stringify(["TNEA"]), established:1951, totalSeats:2500 },
  { name:"BMS College of Engineering", location:"Bangalore, Karnataka", city:"Bangalore", state:"Karnataka", fees:180000, rating:4.2, courses:JSON.stringify(["B.Tech","M.Tech","MBA"]), placement:86.2, avgPackage:1000000, topCompanies:JSON.stringify(["Amazon","Infosys","Bosch","Siemens"]), image:null, tier:"B+", examAccepted:JSON.stringify(["KCET","JEE Main"]), established:1946, totalSeats:2500 },
  { name:"R.V. College of Engineering", location:"Bangalore, Karnataka", city:"Bangalore", state:"Karnataka", fees:170000, rating:4.2, courses:JSON.stringify(["B.Tech","M.Tech"]), placement:86.8, avgPackage:1000000, topCompanies:JSON.stringify(["Amazon","Wipro","Infosys","Intel"]), image:null, tier:"B+", examAccepted:JSON.stringify(["KCET","JEE Main"]), established:1963, totalSeats:2800 },
  { name:"Ramaiah Institute of Technology", location:"Bangalore, Karnataka", city:"Bangalore", state:"Karnataka", fees:155000, rating:4.1, courses:JSON.stringify(["B.Tech","M.Tech","MBA"]), placement:84.3, avgPackage:900000, topCompanies:JSON.stringify(["Bosch","Infosys","TCS","Wipro"]), image:null, tier:"B+", examAccepted:JSON.stringify(["KCET","JEE Main"]), established:1962, totalSeats:3000 },
  { name:"PES University", location:"Bangalore, Karnataka", city:"Bangalore", state:"Karnataka", fees:385000, rating:4.2, courses:JSON.stringify(["B.Tech","M.Tech","MBA"]), placement:85.6, avgPackage:1100000, topCompanies:JSON.stringify(["Amazon","Infosys","Wipro","Accenture"]), image:null, tier:"B+", examAccepted:JSON.stringify(["PESSAT","JEE Main","KCET"]), established:1988, totalSeats:3500 },
  { name:"KJ Somaiya College of Engineering", location:"Mumbai, Maharashtra", city:"Mumbai", state:"Maharashtra", fees:200000, rating:4.0, courses:JSON.stringify(["B.Tech","M.Tech","MBA"]), placement:80.5, avgPackage:800000, topCompanies:JSON.stringify(["Capgemini","Wipro","Infosys","L&T"]), image:null, tier:"B+", examAccepted:JSON.stringify(["MHT CET","JEE Main"]), established:1983, totalSeats:2200 },
  { name:"Chandigarh University", location:"Chandigarh, Punjab", city:"Chandigarh", state:"Punjab", fees:185000, rating:4.0, courses:JSON.stringify(["B.Tech","MBA","MCA","BCA","B.Com"]), placement:82.1, avgPackage:700000, topCompanies:JSON.stringify(["Infosys","Wipro","TCS","Accenture"]), image:null, tier:"B+", examAccepted:JSON.stringify(["CUCET","JEE Main"]), established:2012, totalSeats:15000 },
  { name:"KIIT University", location:"Bhubaneswar, Odisha", city:"Bhubaneswar", state:"Odisha", fees:350000, rating:4.1, courses:JSON.stringify(["B.Tech","MBA","Law","MCA","BCA"]), placement:80.3, avgPackage:750000, topCompanies:JSON.stringify(["Infosys","TCS","Wipro","Accenture"]), image:null, tier:"B+", examAccepted:JSON.stringify(["KIITEE","JEE Main"]), established:1992, totalSeats:8000 },
  { name:"Pune Institute of Computer Technology", location:"Pune, Maharashtra", city:"Pune", state:"Maharashtra", fees:120000, rating:4.2, courses:JSON.stringify(["B.Tech","M.Tech"]), placement:85.0, avgPackage:900000, topCompanies:JSON.stringify(["Persistent","Infosys","Cognizant","Wipro"]), image:null, tier:"B+", examAccepted:JSON.stringify(["MHT CET","JEE Main"]), established:1983, totalSeats:1200 },
  { name:"Nirma University", location:"Ahmedabad, Gujarat", city:"Ahmedabad", state:"Gujarat", fees:265000, rating:4.1, courses:JSON.stringify(["B.Tech","MBA","Law","B.Pharm","M.Tech"]), placement:83.4, avgPackage:900000, topCompanies:JSON.stringify(["Adani","Reliance","Wipro","Infosys"]), image:null, tier:"B+", examAccepted:JSON.stringify(["JEE Main"]), established:2003, totalSeats:4000 },
  { name:"Savitribai Phule Pune University", location:"Pune, Maharashtra", city:"Pune", state:"Maharashtra", fees:50000, rating:4.0, courses:JSON.stringify(["B.Tech","M.Tech","MBA","MCA","B.Sc","M.Sc"]), placement:80.0, avgPackage:750000, topCompanies:JSON.stringify(["Infosys","Wipro","TCS","Persistent"]), image:null, tier:"B+", examAccepted:JSON.stringify(["MHT CET"]), established:1949, totalSeats:5000 },
  { name:"Kalinga Institute of Industrial Technology", location:"Bhubaneswar, Odisha", city:"Bhubaneswar", state:"Odisha", fees:280000, rating:4.0, courses:JSON.stringify(["B.Tech","M.Tech","MBA","MCA"]), placement:79.8, avgPackage:700000, topCompanies:JSON.stringify(["TCS","Wipro","Infosys","Tech Mahindra"]), image:null, tier:"B+", examAccepted:JSON.stringify(["KIITEE"]), established:1992, totalSeats:7000 },
  { name:"Symbiosis Institute of Technology", location:"Pune, Maharashtra", city:"Pune", state:"Maharashtra", fees:420000, rating:4.0, courses:JSON.stringify(["B.Tech","M.Tech","MBA"]), placement:79.4, avgPackage:750000, topCompanies:JSON.stringify(["Infosys","TCS","Wipro","Atos"]), image:null, tier:"B", examAccepted:JSON.stringify(["SET","JEE Main"]), established:2008, totalSeats:1800 },
  { name:"Amity University Noida", location:"Noida, Uttar Pradesh", city:"Noida", state:"Uttar Pradesh", fees:350000, rating:3.9, courses:JSON.stringify(["B.Tech","MBA","BCA","MCA","B.Sc"]), placement:78.5, avgPackage:600000, topCompanies:JSON.stringify(["TCS","Wipro","Infosys","HCL"]), image:null, tier:"B", examAccepted:JSON.stringify(["Amity JEE","JEE Main"]), established:1995, totalSeats:12000 },
  { name:"Lovely Professional University", location:"Phagwara, Punjab", city:"Phagwara", state:"Punjab", fees:200000, rating:3.8, courses:JSON.stringify(["B.Tech","MBA","BCA","MCA","B.Sc"]), placement:74.2, avgPackage:550000, topCompanies:JSON.stringify(["TCS","Wipro","HCL","Infosys"]), image:null, tier:"B", examAccepted:JSON.stringify(["LPUNEST","JEE Main"]), established:2005, totalSeats:20000 },
  { name:"Graphic Era University", location:"Dehradun, Uttarakhand", city:"Dehradun", state:"Uttarakhand", fees:165000, rating:3.9, courses:JSON.stringify(["B.Tech","MBA","MCA","B.Sc"]), placement:76.5, avgPackage:550000, topCompanies:JSON.stringify(["Infosys","Wipro","TCS","Cognizant"]), image:null, tier:"B", examAccepted:JSON.stringify(["JEE Main"]), established:1993, totalSeats:4000 },
  { name:"Osmania University", location:"Hyderabad, Telangana", city:"Hyderabad", state:"Telangana", fees:35000, rating:3.8, courses:JSON.stringify(["B.Tech","MBA","B.Sc","M.Sc","Law","PhD"]), placement:72.5, avgPackage:500000, topCompanies:JSON.stringify(["Infosys","TCS","Wipro","BHEL"]), image:null, tier:"B", examAccepted:JSON.stringify(["TSEAMCET"]), established:1918, totalSeats:4000 },
  { name:"Maharaja Sayajirao University", location:"Vadodara, Gujarat", city:"Vadodara", state:"Gujarat", fees:45000, rating:3.9, courses:JSON.stringify(["B.Tech","MBA","B.Sc","M.Sc","Law"]), placement:73.4, avgPackage:550000, topCompanies:JSON.stringify(["Adani","Reliance","ONGC","BHEL"]), image:null, tier:"B", examAccepted:JSON.stringify(["GUJCET","JEE Main"]), established:1949, totalSeats:3000 },
];

const questions = [
  { title:"What is the cutoff rank for IIT Bombay CSE?", body:"I got JEE Advanced rank 850. Is there a chance for Computer Science at IIT Bombay?", author:"Rohan Mehta", collegeName:"IIT Bombay" },
  { title:"BITS Pilani vs NIT Trichy - which is better for placements?", body:"I have BITSAT score for BITS Pilani and JEE Main rank for NIT Trichy. Which should I choose for better placement opportunities?", author:"Priya Sharma", collegeName:null },
  { title:"How is the MBA program at IIT Delhi?", body:"Planning to do MBA from IIT Delhi. What is the selection process and how are placements compared to IIMs?", author:"Amit Kumar", collegeName:"IIT Delhi" },
  { title:"VIT vs Manipal - campus life and placements?", body:"Both VIT and Manipal are offering me admission. Which has better campus life, faculty, and tech company placements?", author:"Sneha Reddy", collegeName:null },
  { title:"Is IIIT Hyderabad good for research?", body:"I am interested in AI/ML research. How is IIIT Hyderabad's research culture compared to IITs?", author:"Karan Singh", collegeName:"IIIT Hyderabad" },
  { title:"NIT Warangal ECE or DTU CSE - which to pick?", body:"I have both options available. Confused between NIT Warangal ECE and Delhi Technological University CSE. Placement wise which is better?", author:"Rahul Verma", collegeName:null },
  { title:"Hostel facilities at IIT Madras?", body:"How are the hostels at IIT Madras? Are they comfortable? What is the food like on campus?", author:"Ananya Iyer", collegeName:"IIT Madras" },
  { title:"Can I get into IIT Roorkee with JEE rank 8000?", body:"My JEE Advanced rank is 8000. What are my chances at IIT Roorkee and which branches should I target?", author:"Dev Patel", collegeName:"IIT Roorkee" },
];

async function main() {
  console.log("Clearing existing data...");
  await prisma.answer.deleteMany();
  await prisma.question.deleteMany();
  await prisma.college.deleteMany();

  console.log("Seeding colleges...");
  const created = await Promise.all(colleges.map(c => prisma.college.create({ data: c })));
  console.log(`Created ${created.length} colleges`);

  console.log("Seeding Q&A...");
  const collegeMap = Object.fromEntries(created.map(c => [c.name, c.id]));

  for (const q of questions) {
    const question = await prisma.question.create({
      data: {
        title: q.title,
        body: q.body,
        author: q.author,
        collegeId: q.collegeName ? (collegeMap[q.collegeName] ?? null) : null,
      }
    });

    // seed 2 mock answers per question
    await prisma.answer.createMany({
      data: [
        { body: `Great question! Based on my experience, the cutoff varies year to year. I'd suggest checking the official JoSAA data for the last 3 years to get accurate opening and closing ranks.`, author: "Alumni2023", questionId: question.id },
        { body: `Both options are excellent. Consider your preferred location, branch interest, and long-term goals. Visit the campus if possible before deciding!`, author: "CampusoAdvisor", questionId: question.id },
      ]
    });
  }

  const totalQ = await prisma.question.count();
  const totalA = await prisma.answer.count();
  console.log(`Done! ${totalQ} questions, ${totalA} answers seeded.`);
}

main().catch(console.error).finally(() => prisma.$disconnect());
